name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: NuGet restore
      run: nuget restore Elmah.Io.AspNetCore.Analyzers.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build
      run: msbuild Elmah.Io.AspNetCore.Analyzers.sln -p:Configuration=Release
